platform :ios, '10.0'
use_frameworks!

target 'App' do
  # Add your Pods here

  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorZip', :path => '/Users/triniwiz/Documents/oss/capacitor-zip/demo/node_modules/capacitor-zip'
  # Do not delete
end
